# Chargement des données waveshare
On upload notre dataset d'images au format jpg et correctemment nommées, et on le convertit en images et labels au format npy

In [1]:
import os
import sys

from os import listdir
from os.path import isfile, join

import pandas as pd    
import numpy as np
import glob

import seaborn as sns

In [2]:
path_sigma = "C:/Users/afougere/Git/e1/data_analysis/data/files_data/files_catalog/"

l_circuit = ['waveshare/', 'warehouse/', 'generated/', 'mon_circuit/']

path_catalog_waveshare = path_sigma + l_circuit[0]
path_catalog_warehouse = path_sigma + l_circuit[1]
path_catalog_generated = path_sigma + l_circuit[2]
path_catalog_mon_circuit = path_sigma + l_circuit[3]

fichiers_waveshare = [f for f in listdir(path_catalog_waveshare) if isfile(join(path_catalog_waveshare, f))]
fichiers_warehouse = [f for f in listdir(path_catalog_warehouse) if isfile(join(path_catalog_warehouse, f))]
fichiers_generated = [f for f in listdir(path_catalog_generated) if isfile(join(path_catalog_generated, f))]
fichiers_mon_circuit = [f for f in listdir(path_catalog_mon_circuit) if isfile(join(path_catalog_mon_circuit, f))]

fichiers_waveshare

['catalog_0.catalog', 'catalog_1.catalog']

### Transformation des .catalog en .csv

In [3]:
path_sigma_csv = "C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/"

path_catalog_csv_wave = path_sigma_csv + l_circuit[0]
path_catalog_csv_ware = path_sigma_csv + l_circuit[1]
path_catalog_csv_gene = path_sigma_csv + l_circuit[2]
path_catalog_csv_mon_circuit = path_sigma_csv + l_circuit[3]

for i in fichiers_waveshare:

    with open(os.path.join(path_catalog_waveshare  + i), 'r', encoding='cp1252') as f1:
        lines = f1.read()
        f2 = open(os.path.join(path_catalog_csv_wave + i + '.csv' ), 'w', encoding='utf-8')
        f2.write(lines)
        #f2.close()
        
for j in fichiers_warehouse:

    with open(os.path.join(path_catalog_warehouse + j), 'r', encoding='cp1252') as f1:
        lines = f1.read()
        f2 = open(os.path.join(path_catalog_csv_ware +  j + '.csv' ), 'w', encoding='utf-8')
        f2.write(lines)
        #f2.close()
        
for f in fichiers_generated:

    with open(os.path.join(path_catalog_generated + f), 'r', encoding='cp1252') as f1:
        lines = f1.read()
        f2 = open(os.path.join(path_catalog_csv_gene + f + '.csv' ), 'w', encoding='utf-8')
        f2.write(lines)
        #f2.close()
        
        
for f in fichiers_mon_circuit:

    with open(os.path.join(path_catalog_mon_circuit + f), 'r', encoding='cp1252') as f1:
        lines = f1.read()
        f2 = open(os.path.join(path_catalog_csv_mon_circuit + f + '.csv' ), 'w', encoding='utf-8')
        f2.write(lines)
        #f2.close()
    
    
#from IPython.core.debugger import Pdb; Pdb().set_trace()

In [4]:
liste_csv = []

for name in l_circuit:
    url_circuit = os.path.join(path_sigma_csv + name)
    #print(url_image)
    liste_csv.append(url_circuit)

liste_csv

['C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/waveshare/',
 'C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/warehouse/',
 'C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/generated/',
 'C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/mon_circuit/']

In [5]:
# get data file names
files = []
for c in liste_csv:
    #print(c)
    filenames = glob.glob(c + "/" + "*.csv")
    files.append(filenames)
    print(files)
    
type(filenames)

[['C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/waveshare\\catalog_0.catalog.csv', 'C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/waveshare\\catalog_1.catalog.csv']]
[['C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/waveshare\\catalog_0.catalog.csv', 'C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/waveshare\\catalog_1.catalog.csv'], ['C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/warehouse\\catalog_0.catalog.csv', 'C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/warehouse\\catalog_1.catalog.csv']]
[['C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/waveshare\\catalog_0.catalog.csv', 'C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/waveshare\\catalog_1.catalog.csv'], ['C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/warehouse\\catalog_0.catalog.csv', 'C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/warehouse\\catalog_1.catalog.csv'], ['C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/generated\\catalog_0.catalog.csv', 'C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/generated\\catalog_1.catalog.csv']]
[['C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/waveshare\\catalog_0.catalog.csv', 'C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/waveshare\\catalog_1.catalog.csv'], ['C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/warehouse\\catalog_0.catalog.csv', 'C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/warehouse\\catalog_1.catalog.csv'], ['C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/generated\\catalog_0.catalog.csv', 'C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/generated\\catalog_1.catalog.csv'], ['C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/mon_circuit\\catalog_0.catalog.csv', 'C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/mon_circuit\\catalog_1.catalog.csv', 'C:/Users/afougere/Git/e1/data_analysis/data/files_data/catalog_csv/mon_circuit\\catalog_2.catalog.csv']]

list

In [6]:
dfs = []

for file in files:
    for f in file:
        f = pd.read_csv(f, names = ['index', 'timestamp_ms', "cam/image_array", "user/angle", "user/mode", "user/throttle"])
        dfs.append(f)

        # Concatenate all data into one DataFrame
        df = pd.concat(dfs, ignore_index=True)

In [7]:
df

,index,timestamp_ms,cam/image_array,user/angle,user/mode,user/throttle
0,"{""_index"": 0","""_timestamp_ms"": 1616688906607","""cam/image_array"": ""0_cam_image_array_.jpg""","""user/angle"": 0.0","""user/mode"": ""user""","""user/throttle"": 0.040369075887343474}"
1,"{""_index"": 1","""_timestamp_ms"": 1616688906670","""cam/image_array"": ""1_cam_image_array_.jpg""","""user/angle"": 0.0","""user/mode"": ""user""","""user/throttle"": 0.040369075887343474}"
2,"{""_index"": 2","""_timestamp_ms"": 1616688906738","""cam/image_array"": ""2_cam_image_array_.jpg""","""user/angle"": 0.0","""user/mode"": ""user""","""user/throttle"": 0.3171856683843276}"
3,"{""_index"": 3","""_timestamp_ms"": 1616688906797","""cam/image_array"": ""3_cam_image_array_.jpg""","""user/angle"": 0.0","""user/mode"": ""user""","""user/throttle"": 0.3171856683843276}"
4,"{""_index"": 4","""_timestamp_ms"": 1616688906861","""cam/image_array"": ""4_cam_image_array_.jpg""","""user/angle"": 0.0","""user/mode"": ""user""","""user/throttle"": 0.3264128881342271}"
...,...,...,...,...,...,...
6347,"""_session_id"": ""21-05-21_0""","""_timestamp_ms"": 1621604653261","""cam/image_array"": ""1995_cam_image_array_.jpg""","""user/angle"": -1.0","""user/mode"": ""user""","""user/throttle"": 0.2}"
6348,"""_session_id"": ""21-05-21_0""","""_timestamp_ms"": 1621604653316","""cam/image_array"": ""1996_cam_image_array_.jpg""","""user/angle"": -1.0","""user/mode"": ""user""","""user/throttle"": 0.2}"
6349,"""_session_id"": ""21-05-21_0""","""_timestamp_ms"": 1621604653362","""cam/image_array"": ""1997_cam_image_array_.jpg""","""user/angle"": -1.0","""user/mode"": ""user""","""user/throttle"": 0.2}"
6350,"""_session_id"": ""21-05-21_0""","""_timestamp_ms"": 1621604653421","""cam/image_array"": ""1998_cam_image_array_.jpg""","""user/angle"": -1.0","""user/mode"": ""user""","""user/throttle"": 0.2}"
6351,"""_session_id"": ""21-05-21_0""","""_timestamp_ms"": 1621604653462","""cam/image_array"": ""1999_cam_image_array_.jpg""","""user/angle"": -1.0","""user/mode"": ""user""","""user/throttle"": 0.2}"

In [8]:
liste_index = df['index'].tolist()
liste_time = df['timestamp_ms'].tolist()
liste_cam = df['cam/image_array'].tolist()
liste_angle = df['user/angle'].tolist()
liste_mode = df['user/mode'].tolist()
liste_throttle = df['user/throttle'].tolist()

In [9]:
liste_index_result = []
l_timestamp = []
l_cam_image_array = []
l_user_mode = []
l_user_angle = []
l_user_throttle = []

for i in range(6352):
    
    liste_index_result.append(liste_index[i].split(':')[1])
    l_timestamp.append(liste_time[i].split(':')[1])
    l_cam_image_array.append(liste_cam[i].split(':')[1])
    l_user_mode.append(liste_mode[i].split(':')[1])
    l_user_angle.append(liste_angle[i].split(':')[1])
    l_user_throttle.append(liste_throttle[i].split(':')[1])

In [10]:
df.head()

,index,timestamp_ms,cam/image_array,user/angle,user/mode,user/throttle
0,"{""_index"": 0","""_timestamp_ms"": 1616688906607","""cam/image_array"": ""0_cam_image_array_.jpg""","""user/angle"": 0.0","""user/mode"": ""user""","""user/throttle"": 0.040369075887343474}"
1,"{""_index"": 1","""_timestamp_ms"": 1616688906670","""cam/image_array"": ""1_cam_image_array_.jpg""","""user/angle"": 0.0","""user/mode"": ""user""","""user/throttle"": 0.040369075887343474}"
2,"{""_index"": 2","""_timestamp_ms"": 1616688906738","""cam/image_array"": ""2_cam_image_array_.jpg""","""user/angle"": 0.0","""user/mode"": ""user""","""user/throttle"": 0.3171856683843276}"
3,"{""_index"": 3","""_timestamp_ms"": 1616688906797","""cam/image_array"": ""3_cam_image_array_.jpg""","""user/angle"": 0.0","""user/mode"": ""user""","""user/throttle"": 0.3171856683843276}"
4,"{""_index"": 4","""_timestamp_ms"": 1616688906861","""cam/image_array"": ""4_cam_image_array_.jpg""","""user/angle"": 0.0","""user/mode"": ""user""","""user/throttle"": 0.3264128881342271}"

In [11]:
df2 = pd.DataFrame({'timestamp_ms' : l_timestamp, "cam/image_array" : l_cam_image_array, "user/angle" : l_user_angle, "user/mode" : l_user_mode, "user/throttle" : l_user_throttle})

In [12]:
df2

,timestamp_ms,cam/image_array,user/angle,user/mode,user/throttle
0,1616688906607,"""0_cam_image_array_.jpg""",0.0,"""user""",0.040369075887343474}
1,1616688906670,"""1_cam_image_array_.jpg""",0.0,"""user""",0.040369075887343474}
2,1616688906738,"""2_cam_image_array_.jpg""",0.0,"""user""",0.3171856683843276}
3,1616688906797,"""3_cam_image_array_.jpg""",0.0,"""user""",0.3171856683843276}
4,1616688906861,"""4_cam_image_array_.jpg""",0.0,"""user""",0.3264128881342271}
...,...,...,...,...,...
6347,1621604653261,"""1995_cam_image_array_.jpg""",-1.0,"""user""",0.2}
6348,1621604653316,"""1996_cam_image_array_.jpg""",-1.0,"""user""",0.2}
6349,1621604653362,"""1997_cam_image_array_.jpg""",-1.0,"""user""",0.2}
6350,1621604653421,"""1998_cam_image_array_.jpg""",-1.0,"""user""",0.2}
6351,1621604653462,"""1999_cam_image_array_.jpg""",-1.0,"""user""",0.2}

In [13]:
len(df2)

6352

In [14]:
l_cam_image_array_2 = []
l_user_mode_2 = []
l_user_throttle_2 = []
#l_user_angle_2 = []

for i in range(len(df2)):
    l_cam_image_array_2.append(df2.loc[i,"cam/image_array"].replace('"',""))
    l_user_mode_2.append(df2.loc[i,"user/mode"].replace('"',""))
    l_user_throttle_2.append(df2.loc[i,"user/throttle"].replace('}',""))
    #l_user_angle_2.append(df.loc[i,"user/angle"].replace('.0',""))

In [15]:
df3 = pd.DataFrame({'timestamp_ms' : l_timestamp, "cam/image_array" : l_cam_image_array_2, "user/angle" : l_user_angle, "user/mode" : l_user_mode_2, "user/throttle" : l_user_throttle_2})

In [16]:
df3.head()

,timestamp_ms,cam/image_array,user/angle,user/mode,user/throttle
0,1616688906607,0_cam_image_array_.jpg,0.0,user,0.040369075887343474
1,1616688906670,1_cam_image_array_.jpg,0.0,user,0.040369075887343474
2,1616688906738,2_cam_image_array_.jpg,0.0,user,0.3171856683843276
3,1616688906797,3_cam_image_array_.jpg,0.0,user,0.3171856683843276
4,1616688906861,4_cam_image_array_.jpg,0.0,user,0.3264128881342271

In [17]:
df3.dtypes

timestamp_ms       object
cam/image_array    object
user/angle         object
user/mode          object
user/throttle      object
dtype: object

In [18]:
df3['user/angle'] = pd.to_numeric(df3['user/angle'], errors='coerce')
df3['user/throttle'] = pd.to_numeric(df3['user/throttle'], errors='coerce')

In [19]:
liste_angle =df3['user/angle'].tolist()
liste_throttle =df3['user/throttle'].tolist()

In [20]:
liste_throttle_better = []

for i in liste_throttle:
    #print(round(i,2))
    liste_throttle_better.append(round(i,1))
    
#liste_throttle_better

In [21]:
liste_angle_better = []

for i in liste_angle:
    #print(round(i,2))
    liste_angle_better.append(round(i, 1))
    
#liste_angle_better

In [22]:
liste_name = []

for i in range(1040):
    liste_name.append("waveshare")
    
for i in range(1808):
    liste_name.append("warehouse")
        
for i in range(1504):
    liste_name.append("generated")   
    
for i in range(2000):
    liste_name.append("mon_circuit")

In [23]:
result_waveshare = pd.DataFrame({'index' : liste_index_result, 'timestamp_ms' : l_timestamp, "cam/image_array" : l_cam_image_array_2, "user/angle" : liste_angle_better, "user/mode" : l_user_mode_2 , "user/throttle" : liste_throttle_better , "circuit" : liste_name})

In [24]:
result_waveshare.head()

,index,timestamp_ms,cam/image_array,user/angle,user/mode,user/throttle,circuit
0,0,1616688906607,0_cam_image_array_.jpg,0.0,user,0.0,waveshare
1,1,1616688906670,1_cam_image_array_.jpg,0.0,user,0.0,waveshare
2,2,1616688906738,2_cam_image_array_.jpg,0.0,user,0.3,waveshare
3,3,1616688906797,3_cam_image_array_.jpg,0.0,user,0.3,waveshare
4,4,1616688906861,4_cam_image_array_.jpg,0.0,user,0.3,waveshare

### Export du dataframe "result_all_circuit" dans le dossier "stockage_dataframe"

In [25]:
path_dataframe_sigma = 'C:/Users/afougere/Git/e1/data_analysis/data/dataframe_data'

In [26]:
result_waveshare.to_csv('../data/dataframe_data/result_all_circuit.csv', index = False)

In [27]:
df = pd.read_csv('../data/dataframe_data/result_all_circuit.csv')

In [28]:
df.head()

,index,timestamp_ms,cam/image_array,user/angle,user/mode,user/throttle,circuit
0,0,1616688906607,0_cam_image_array_.jpg,0.0,user,0.0,waveshare
1,1,1616688906670,1_cam_image_array_.jpg,0.0,user,0.0,waveshare
2,2,1616688906738,2_cam_image_array_.jpg,0.0,user,0.3,waveshare
3,3,1616688906797,3_cam_image_array_.jpg,0.0,user,0.3,waveshare
4,4,1616688906861,4_cam_image_array_.jpg,0.0,user,0.3,waveshare

## Drop de la colonne index du dataframe "circuit"

In [29]:
df = df.drop(["index"], axis=1)
df.head()

,timestamp_ms,cam/image_array,user/angle,user/mode,user/throttle,circuit
0,1616688906607,0_cam_image_array_.jpg,0.0,user,0.0,waveshare
1,1616688906670,1_cam_image_array_.jpg,0.0,user,0.0,waveshare
2,1616688906738,2_cam_image_array_.jpg,0.0,user,0.3,waveshare
3,1616688906797,3_cam_image_array_.jpg,0.0,user,0.3,waveshare
4,1616688906861,4_cam_image_array_.jpg,0.0,user,0.3,waveshare

### Nettoyage du df_main en enlevant les valeurs 0 dans la colonne throttle

len(circuit.loc[circuit['user/throttle'] == 0])

# Conversion de timestamp en secondes

In [30]:
df['timestamp_ms'] = pd.to_numeric(df['timestamp_ms'], errors='coerce')

In [31]:
liste_timestamp = df['timestamp_ms'].tolist()

In [32]:
l_secondes = []

for i in liste_timestamp:
    #print(i/1000)
    i = i/1000
    l_secondes.append(i)
    
    
#l_secondes

In [33]:
liste_time = []
import time
for i in l_secondes:
    readable = time.ctime(i)
    liste_time.append(readable)
    
#liste_time

# Création de la colonne date

In [34]:
df['date'] = liste_time

In [35]:
df.tail()

,timestamp_ms,cam/image_array,user/angle,user/mode,user/throttle,circuit,date
6347,1621604653261,1995_cam_image_array_.jpg,-1.0,user,0.2,mon_circuit,Fri May 21 15:44:13 2021
6348,1621604653316,1996_cam_image_array_.jpg,-1.0,user,0.2,mon_circuit,Fri May 21 15:44:13 2021
6349,1621604653362,1997_cam_image_array_.jpg,-1.0,user,0.2,mon_circuit,Fri May 21 15:44:13 2021
6350,1621604653421,1998_cam_image_array_.jpg,-1.0,user,0.2,mon_circuit,Fri May 21 15:44:13 2021
6351,1621604653462,1999_cam_image_array_.jpg,-1.0,user,0.2,mon_circuit,Fri May 21 15:44:13 2021

In [36]:
df.dtypes

timestamp_ms         int64
cam/image_array     object
user/angle         float64
user/mode           object
user/throttle      float64
circuit             object
date                object
dtype: object

In [37]:
df.head()

,timestamp_ms,cam/image_array,user/angle,user/mode,user/throttle,circuit,date
0,1616688906607,0_cam_image_array_.jpg,0.0,user,0.0,waveshare,Thu Mar 25 17:15:06 2021
1,1616688906670,1_cam_image_array_.jpg,0.0,user,0.0,waveshare,Thu Mar 25 17:15:06 2021
2,1616688906738,2_cam_image_array_.jpg,0.0,user,0.3,waveshare,Thu Mar 25 17:15:06 2021
3,1616688906797,3_cam_image_array_.jpg,0.0,user,0.3,waveshare,Thu Mar 25 17:15:06 2021
4,1616688906861,4_cam_image_array_.jpg,0.0,user,0.3,waveshare,Thu Mar 25 17:15:06 2021

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6352 entries, 0 to 6351
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   timestamp_ms     6352 non-null   int64
 1   cam/image_array  6352 non-null   object
 2   user/angle       6352 non-null   float64
 3   user/mode        6352 non-null   object
 4   user/throttle    6352 non-null   float64
 5   circuit          6352 non-null   object
 6   date             6352 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 347.5+ KB

# Création des sept tables

## Création de la première table : "direction"

In [39]:
lst1 = ['left', 'straight', 'right']

df_direction = pd.DataFrame(list(zip(lst1)), columns = ['direction'])
df_direction

  direction
0      left
1  straight
2     right

## Création de la deuxième table : "puissance"

In [40]:
lst_puissance = ['moving forward', 'dead point', 'moving back']

df_puissance = pd.DataFrame(list(zip(lst_puissance)), columns = ['puissance'])
df_puissance

        puissance
0  moving forward
1      dead point
2     moving back

## Création de la troisième table : "valeurs_angle"

In [41]:
lst_angle = [-1, -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0 , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]

df_valeurs_angle = pd.DataFrame(list(zip(lst_angle)), columns = ['angle'])
df_valeurs_angle

    angle
0    -1.0
1    -0.9
2    -0.8
3    -0.7
4    -0.6
5    -0.5
6    -0.4
7    -0.3
8    -0.2
9    -0.1
10    0.0
11    0.1
12    0.2
13    0.3
14    0.4
15    0.5
16    0.6
17    0.7
18    0.8
19    0.9
20    1.0

## Création de la quatrième table : "valeurs_throttle"

In [42]:
lst_throttle = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]

df_valeurs_throttle = pd.DataFrame(list(zip(lst_throttle)), columns = ['throttle'])
df_valeurs_throttle

    throttle
0        0.0
1        0.1
2        0.2
3        0.3
4        0.4
5        0.5
6        0.6
7        0.7
8        0.8
9        0.9
10       1.0

## Création de la cinquième table : "circuit"

In [43]:
lst_circuit = ['waveshare', 'warehouse', 'generated', 'mon_circuit']

df_circuit = pd.DataFrame(list(zip(lst_circuit)), columns = ['circuit'])
df_circuit

       circuit
0    waveshare
1    warehouse
2    generated
3  mon_circuit

## sixième table : "table principale : df "

In [44]:
df.tail()

,timestamp_ms,cam/image_array,user/angle,user/mode,user/throttle,circuit,date
6347,1621604653261,1995_cam_image_array_.jpg,-1.0,user,0.2,mon_circuit,Fri May 21 15:44:13 2021
6348,1621604653316,1996_cam_image_array_.jpg,-1.0,user,0.2,mon_circuit,Fri May 21 15:44:13 2021
6349,1621604653362,1997_cam_image_array_.jpg,-1.0,user,0.2,mon_circuit,Fri May 21 15:44:13 2021
6350,1621604653421,1998_cam_image_array_.jpg,-1.0,user,0.2,mon_circuit,Fri May 21 15:44:13 2021
6351,1621604653462,1999_cam_image_array_.jpg,-1.0,user,0.2,mon_circuit,Fri May 21 15:44:13 2021

## Création de la septième table : "path"

In [45]:
from zipfile import ZipFile

In [46]:
path_images_sigma = "C:/Users/afougere/Git/e1/data_analysis/data/images_data/images/circuits/"

In [47]:
# spécifiant le nom du fichier zip
file_waveshare = "../data/images_data/images/circuits/waveshare.zip"
file_warehouse = "../data/images_data/images/circuits/warehouse.zip"
file_generated = "../data/images_data/images/circuits/generated.zip"
file_mon_circuit = "../data/images_data/images/circuits/mon_circuit.zip"

a = [file_waveshare, file_warehouse, file_generated, file_desert]

for i in a :
    # ouvrir le fichier zip en mode lecture
    with ZipFile(i, 'r') as zip: 
        # afficher tout le contenu du fichier zip
        zip.printdir() 
  
        # extraire tous les fichiers
        print('extraction...') 
        zip.extractall("../data/images_data/images/circuits") 
        print('Terminé!')

NameError: name 'file_desert' is not defined

In [ ]:
import os
from os import listdir
from os.path import isfile, join

path_waveshare = path_images_sigma + l_circuit[0]
path_warehouse = path_images_sigma + l_circuit[1]
path_generated = path_images_sigma + l_circuit[2]
path_mon_circuit = path_images_sigma + l_circuit[3]

images_waveshare = [f for f in listdir(path_waveshare) if isfile(join(path_waveshare, f))]
images_warehouse = [f for f in listdir(path_warehouse) if isfile(join(path_warehouse, f))]
images_generated = [f for f in listdir(path_generated) if isfile(join(path_generated, f))]
images_mon_circuit = [f for f in listdir(path_mon_circuit) if isfile(join(path_mon_circuit, f))]


images_tot = images_waveshare + images_warehouse + images_generated + images_mon_circuit
len(images_tot)

In [ ]:
liste_pict = []

for image in images_tot:
        
    url_image = os.path.join(path_images_sigma, image)
    liste_pict.append(url_image)
    
len(liste_pict)
#liste_pict_waveshare[0]

In [ ]:
df_path = pd.DataFrame(list(liste_pict), columns = ['path'])
df_path.tail()

In [ ]:
len(df_path)

# Export de mes 7 tables dans le dossier "tables_csv"

In [ ]:
df_direction.to_csv('../data/dataframe_data/tables/table_direction.csv', index = False)
df_puissance.to_csv('../data/dataframe_data/tables/table_puissance.csv', index = False)
df_valeurs_angle.to_csv('../data/dataframe_data/tables/table_valeurs_angle.csv', index = False)
df_valeurs_throttle.to_csv('../data/dataframe_data/tables/table_valeurs_throttle.csv', index = False)
df_circuit.to_csv('../data/dataframe_data/tables/table_circuit.csv', index = False)
df.to_csv('../data/dataframe_data/tables/table_principale.csv', index = False, sep = ",")
df_path.to_csv('../data/dataframe_data/tables/table_path.csv', index = False, sep = ",")